# name: Ejecutar main.py cada hora

# on:
#   schedule:
#     - cron: '0 * * * *'  # Se ejecuta cada hora
#   workflow_dispatch:  # Permite ejecución manual

# jobs:
#   run_script:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Clonar el repositorio
#         uses: actions/checkout@v4

#       - name: Configurar Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Instalar dependencias
#         run: |
#           python -m venv venv
#           source venv/bin/activate
#           pip install --upgrade pip
#           pip install python-dotenv
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#       - name: Verificar paquetes instalados
#         run: |
#           source venv/bin/activate
#           pip list

#       - name: Ejecutar el script con variables de entorno
#         run: |
#           source venv/bin/activate
#           python main.py
#         env:
#           API_KEY: ${{ secrets.API_KEY }}
